In [1]:
import pandas as pd
import codecs

In [20]:
with codecs.open("../data/input/JPvideos.csv", "r", "utf-8", "ignore") as file:
    df = pd.read_table(file, delimiter=",")
channel_id = pd.read_csv("../data/input/channel_id.csv")
channel_id = channel_id[["video_id", "channel_id"]]
df = df[["video_id", "title"]]

In [21]:
channel_id["channel_id"]

0       UCNLxBzguoGLqXWA8_BtHSHA
1                        No Data
2       UCtI0Hodo5o5dUb67FeUjDeA
3                        No Data
4       UCRxDTCmIjgli-Xgh2KPE9dA
                  ...
8157                     No Data
8158                     No Data
8159                     No Data
8160    UC72bkkvKulLl_muXs0ygF_Q
8161    UC1cHlPIE-kqiPvpyYz2O8rQ
Name: channel_id, Length: 8162, dtype: object

In [24]:
channel_id = channel_id[channel_id["channel_id"]!="No Data"]

In [5]:
df

          video_id                                              title
0      5ugKfHgsmYw                                 陸自ヘリ、垂直に落下＝路上の車が撮影
1      ohObafdd34Y                             イッテQ お祭り男宮川×手越 巨大ブランコ②
2      aBr2kKAHN6M                              Live Views of Starman
3      5wNnwChvmsQ                         東京ディズニーリゾートの元キャストが暴露した秘密5選
4      B7J47qFvdsk          榮倉奈々、衝撃の死んだふり！映画『家に帰ると妻が必ず死んだふりをしています。』特報
...            ...                                                ...
20518  GuWCkLnCMOo  หนึ่งด้าวฟ้าเดียว NeungDaoFahDeaw EP.15 ตอนที่...
20519  nOUlB0i2MaA  2018 국민의 선택 - 선거방송 '왕의 귀환' 12시간 연속 생중계! (풀영상) ...
20520  4cRanIowkTE            元FBIエージェントが教える、200％人を引き付けるようになるコツ、トップ10
20521  oLtWIVBVoS8     日本×パラグアイ徹底分析&スペイン代表監督解任事件を解説【トークtheフットボール】#683
20522  2IEWv23oa9E                             エサのコオロギに夢中で二本足で立つカメレオン

[20523 rows x 2 columns]

In [31]:
channel_id

         video_id                channel_id
0     5ugKfHgsmYw  UCNLxBzguoGLqXWA8_BtHSHA
2     aBr2kKAHN6M  UCtI0Hodo5o5dUb67FeUjDeA
4     B7J47qFvdsk  UCRxDTCmIjgli-Xgh2KPE9dA
9     FVPmVIfl3-o  UC-km1012mEUQQLGxggmrazw
10    CcWHJuzPUKY  UC72bkkvKulLl_muXs0ygF_Q
...           ...                       ...
8153  rvdHznn2wzI  UCvmppcdYf4HOv-tFQhHHJMA
8154  BwN04BZy7PQ  UCroloVlHKUnvOMn5MtuvyDg
8156  owseTngZFMI  UCg3qsVzHeUt5_cPpcRtoaJQ
8160  FuXehxqFH6c  UC72bkkvKulLl_muXs0ygF_Q
8161  dMQUitVdNdo  UC1cHlPIE-kqiPvpyYz2O8rQ

[4243 rows x 2 columns]

In [33]:
pd.merge(df, channel_id).drop_duplicates()

,video_id,title,channel_id
0,5ugKfHgsmYw,陸自ヘリ、垂直に落下＝路上の車が撮影,UCNLxBzguoGLqXWA8_BtHSHA
64,aBr2kKAHN6M,Live Views of Starman,UCtI0Hodo5o5dUb67FeUjDeA
80,B7J47qFvdsk,榮倉奈々、衝撃の死んだふり！映画『家に帰ると妻が必ず死んだふりをしています。』特報,UCRxDTCmIjgli-Xgh2KPE9dA
96,FVPmVIfl3-o,究極の激ウマ丼の作り方。,UC-km1012mEUQQLGxggmrazw
112,CcWHJuzPUKY,シャンシャン238日齢（2）2018年2月5日撮影,UC72bkkvKulLl_muXs0ygF_Q
...,...,...,...
8670,YkUgd1ALN0I,【替え歌】2億4千万の瞳『2万4千円の家賃』- 郷ひろみ うた：たすくこま,UCxkjgt_ePhbOoCRPr0szT8Q
8676,rvdHznn2wzI,【にじさんじ公式】女神のましゅまろ１,UCvmppcdYf4HOv-tFQhHHJMA
8682,BwN04BZy7PQ,遊びたくて仕方ない柴犬、遊ばないけどいつも近くにいる猫 Playful shibainu,UCroloVlHKUnvOMn5MtuvyDg
8688,FuXehxqFH6c,シャンシャン286日齢（2）2018年3月25日撮影,UC72bkkvKulLl_muXs0ygF_Q
8694,dMQUitVdNdo,ジャニーズJr.チャンネル発表会見【その1】,UC1cHlPIE-kqiPvpyYz2O8rQ

In [34]:
channel_id.drop_duplicates()

         video_id                channel_id
0     5ugKfHgsmYw  UCNLxBzguoGLqXWA8_BtHSHA
2     aBr2kKAHN6M  UCtI0Hodo5o5dUb67FeUjDeA
4     B7J47qFvdsk  UCRxDTCmIjgli-Xgh2KPE9dA
9     FVPmVIfl3-o  UC-km1012mEUQQLGxggmrazw
10    CcWHJuzPUKY  UC72bkkvKulLl_muXs0ygF_Q
...           ...                       ...
8092  YkUgd1ALN0I  UCxkjgt_ePhbOoCRPr0szT8Q
8093  rvdHznn2wzI  UCvmppcdYf4HOv-tFQhHHJMA
8094  BwN04BZy7PQ  UCroloVlHKUnvOMn5MtuvyDg
8100  FuXehxqFH6c  UC72bkkvKulLl_muXs0ygF_Q
8101  dMQUitVdNdo  UC1cHlPIE-kqiPvpyYz2O8rQ

[2640 rows x 2 columns]